image: maven:3.8.6-openjdk-17

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - apt-get update -qq && apt-get install -y -qq git

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - backend-spring-boot/target/*.jar
      - frontend-angular/dist/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    - cd frontend-angular
    - npm install
    - npm test -- --watch=false

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - master

after_script:
  - echo "Build finished"
