stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - docker/

test:
  stage: test
  script:
    - docker-compose up -d
    - sleep 10
    - curl http://localhost:80/api/voters
    - docker-compose down

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker-compose up -d --force-recreate